---
title: "Experiment0_varying_nominalq"
author: "Mark Milner"
date: "2025-01-31"
output: ''
---

This experiment considers changing the prescribed accepted level of FDR.

```{r}
library(knockoff)
```

```{r}
fdp = function(selected, beta) {
  sum(beta[selected] == 0) / max(1, length(selected))
}
```

```{r}
power = function(selected, beta) {
  # True Positives: selected variables with non-zero coefficients
  TP = sum(beta[selected] != 0)
  
  # Total Relevant Variables
  T = sum(beta != 0)
  
  # Compute Power
  TP / T
}
```

# Implimentation

To impliment this, we will consider a variety of FDR control values, namely 0.01, 0.05, 0.1, 0.2, 0.5. By default, we have that FDR=0.1

```{r}
generate_synthetic_data <- function(n=1000, p=1000, relevant_count=100, amplitude=4.5, rho=0.25) {
  mu = rep(0,p)
  Sigma = toeplitz(rho^(0:(p-1)))
  X = matrix(rnorm(n*p),n) %*% chol(Sigma)
  nonzero = sample(p, relevant_count)
  beta = amplitude * (1:p %in% nonzero) / sqrt(n)
  y =  X %*% beta + rnorm(n)
  list(X = X, y = y, beta=beta)
}
```

```{r}
nominals = c(0.01,0.05,0.1,0.2,0.5)
fdp_s = c()
power_s = c()
data <- generate_synthetic_data()
X <- data$X
y <- data$y
beta <- data$beta
for (nominal in nominals) {
  result = knockoff.filter(X, y, fdr=nominal)
  current_fdp = fdp(result$selected, beta)
  current_power = power(result$selected, beta)
  fdp_s = c(fdp_s, current_fdp)
  power_s = c(power_s, current_power)
}
```

```{r}
fdp_s
power_s
```


# Visualisation 

```{r}
plot(nominals, fdp_s, type = "o", col = "red", pch = 16, lty = 1,
     xlab = "nominal q", ylab = "FDP",
     main = "FDP vs nominal q")

plot(nominals, power_s, type = "o", col = "blue", pch = 16, lty = 1,
     xlab = "nominal q", ylab = "Power",
     main = "Power vs nominal q")

```
If i were to run the experiment a large number of times, i would expect the FDP value to tend to the nominal level of q





```{r}

```

