---
title: "Knockoff_method_experiment1"
author: "Mark Milner"
date: "2025-01-19"
output: html_document
---

This experiment considers the number of samples (rows). larger sample means moe info about the population more precice estimates of model parameters. 
By default, our fdr is 0.10

```{r}
library(knockoff)
```

```{r}
fdp = function(selected) sum(beta[selected] == 0) / max(1, length(selected))
```

```{r}
power = function(selected) {
  # True Positives: selected variables with non-zero coefficients
  TP = sum(beta[selected] != 0)
  
  # Total Relevant Variables
  T = sum(beta != 0)
  
  # Compute Power
  TP / T
}
```

## Data Setup 

```{r}
set.seed(21)
```

```{r}
generate_synthetic_data <- function(n, p, relevant_count, amplitude, rho) {
  # Generating the covariance matrix Sigma
  mu <- rep(0, p)
  Sigma <- toeplitz(rho^(0:(p-1)))
  # Generating the covariate data matrix X
  X <- matrix(rnorm(n * p), n) %*% chol(Sigma)
  # Identifying relevant variables
  nonzero <- sample(p, relevant_count)
  # Generating coefficients for the linear model
  beta <- amplitude * (1:p %in% nonzero) / sqrt(n)
  # Function to generate target variable y
  # Generating the target data
  y <- y.sample(X)
  # Returning the design matrix X and target y
  list(X = X, y = y)
}

y.sample <- function(X) X %*% beta + rnorm(n)

```

```{r}
n <- 1000
p <- 1000
relevant_count <- 60
amplitude <- 4.5
rho <- 0.25
data <- generate_synthetic_data(n, p, relevant_count, amplitude, rho)
X <- data$X
y <- data$y
result_default = knockoff.filter(X, y)
result_default$selected
fdp(result_default$selected)
power(result_default$selected)
```

```{r}
n <- 1000
p <- 1000
relevant_count <- 200
amplitude <- 4.5
rho <- 0.25
data <- generate_synthetic_data(n, p, relevant_count, amplitude, rho)
X_large <- data$X
y_large <- data$y
result_large = knockoff.filter(X, y)
result_large$selected
fdp(result_large$selected)
power(result_large$selected)
```

```{r}
n <- 1000
p <- 1000
relevant_count <- 500
amplitude <- 4.5
rho <- 0.25
data <- generate_synthetic_data(n, p, relevant_count, amplitude, rho)
X_larger <- data$X
y_larger <- data$y
result_larger= knockoff.filter(X, y)
result_larger$selected
fdp(result_larger$selected) # did we think some variables were truely relevant when they weren't in reality.
power(result_larger$selected) # did we collect all the truely relevant variables
```

```{r}
n <- 1000
p <- 1000
relevant_count <- 1000
amplitude <- 4.5
rho <- 0.25
data <- generate_synthetic_data(n, p, relevant_count, amplitude, rho)
X_largest <- data$X
y_largest <- data$y
result_largest = knockoff.filter(X, y)
result_largest$selected
fdp(result_largest$selected) # did we think some variables were truely relevant when they weren't in reality.
power(result_largest$selected) # did we collect all the truely relevant variables
```

