---
xtitle: "Biomarker_nominal_test"
author: "Mark Milner"
date: "2025-02-17"
output: html_document
---

```{r}
library(glmnet) # is needed for the linear interaction KO filter 
#library(grf) # is needed for the causal forest (CF) variable importance KO filter 
library(knockoff) # is needed for generating the knockoffs and calculating the threshold
source("C:\\Users\\markm\\OneDrive\\Documents\\University\\Year 4\\Project\\Software\\Variable-Selection-With-Knock-Offs\\Research\\Biomarker Simulation Study\\biomarker_functions.R")

```

```{r}
synthetic_data = generate_scenarios_predictive(scenario = 'S1', model = 'M6', 
sample_size = 1000, num_features = 1000, predictive_amplitude = 1)
paste('In this synthetic dataset the following variables are predictive:', 
paste(synthetic_data$predictive, collapse=","))
```
```{r}
X_tilde = data.frame(create.second_order(as.matrix(synthetic_data$X)))
```
```{r}
selected_with_linear_filter = linear_model_predictive_filter(synthetic_data$X, X_tilde,
synthetic_data$y, synthetic_data$t, fdr_nominal = 0.10, family = 'gaussian')
paste('The linear interaction KO filter returns the variables:',
paste(selected_with_linear_filter, collapse=","))
```

```{r}
power_result = power(selected_with_linear_filter, synthetic_data$predictive)
fdp_result = fdp(selected_with_linear_filter, synthetic_data$predictive )
```

# Experiment

```{r}
q_s = c(0.01,0.05,0.1,0.2,0.5)

results_fdp_l = c()
results_power_l = c()
results_fdp_cf = c()
results_power_cf = c()

synthetic_data = generate_scenarios_predictive(scenario = 'S1', model = 'M6', 
sample_size = 1000, num_features = 1000, predictive_amplitude = 1)


paste('In this synthetic dataset the following variables are predictive:', 
paste(synthetic_data$predictive, collapse=","))

for (q in q_s){
  X_tilde = data.frame(create.second_order(as.matrix(synthetic_data$X)))
  selected_with_linear_filter = linear_model_predictive_filter(synthetic_data$X, X_tilde,
synthetic_data$y, synthetic_data$t, fdr_nominal = q, family = 'gaussian')
  
  selected_with_cf_filter = causal_forest_predictive_filter(synthetic_data$X, X_tilde,
synthetic_data$y, synthetic_data$t, fdr_nominal = q, family = 'gaussian')
  
  
  power_result_l = power(selected_with_linear_filter, synthetic_data$predictive)
  fdp_result_l = fdp(selected_with_linear_filter, synthetic_data$predictive )
  results_fdp_l = c(results_fdp_l, fdp_result_l)
  results_power_l = c(results_power_l, power_result_l)
  
  power_result_cf = power(selected_with_cf_filter, synthetic_data$predictive)
  fdp_result_cf = fdp(selected_with_cf_filter, synthetic_data$predictive )
  results_fdp_cf = c(results_fdp_cf, fdp_result_cf)
  results_power_cf = c(results_power_cf, power_result_cf)
  
}

```

```{r}
plot(q_s, results_fdp_cf, type = "o", col = "red", pch = 16, lty = 1,
     xlab = "q", ylab = "FDP",
     main = "nominal q vs FDP ")

plot(q_s, results_power_cf, type = "o", col = "blue", pch = 16, lty = 1,
     xlab = "q", ylab = "Power",
     main = "nominal q vs Power")

```
# Performing multiple iterations

```{r}
# Define nominal FDR values and number of repetitions
q_s = c(0.01, 0.05, 0.1, 0.2, 0.5)  # Nominal FDR values
num_reps = 5  # Number of repetitions per q

# Initialize vectors to store results for Linear Model and Causal Forest
fdp_means_lm = c()
power_means_lm = c()
fdp_ci_lower_lm = c()
fdp_ci_upper_lm = c()
power_ci_lower_lm = c()
power_ci_upper_lm = c()

fdp_means_cf = c()
power_means_cf = c()
fdp_ci_lower_cf = c()
fdp_ci_upper_cf = c()
power_ci_lower_cf = c()
power_ci_upper_cf = c()

# Generate synthetic data
synthetic_data = generate_scenarios_predictive(scenario = 'S1', model = 'M6', 
                                              sample_size = 1000, num_features = 1000, predictive_amplitude = 1)

# Print predictive variables
print(paste('In this synthetic dataset the following variables are predictive:', 
            paste(synthetic_data$predictive, collapse = ",")))

# Loop over nominal FDR values
for (q in q_s) {
  fdp_repeats_lm = c()
  power_repeats_lm = c()
  fdp_repeats_cf = c()
  power_repeats_cf = c()
  
  # Repeat the experiment 5 times
  for (i in 1:num_reps) {
    # Create second-order knockoffs
    X_tilde = data.frame(create.second_order(as.matrix(synthetic_data$X)))
    
    # Apply Linear Model Predictive Filter
    selected_with_linear_filter = linear_model_predictive_filter(synthetic_data$X, X_tilde,
                                                                synthetic_data$y, synthetic_data$t, fdr_nominal = q, family = 'gaussian')
    current_fdp_lm = fdp(selected_with_linear_filter, synthetic_data$predictive)  # Compute FDP for Linear Model
    current_power_lm = power(selected_with_linear_filter, synthetic_data$predictive)  # Compute Power for Linear Model
    fdp_repeats_lm = c(fdp_repeats_lm, current_fdp_lm)
    power_repeats_lm = c(power_repeats_lm, current_power_lm)
    
    # Apply Causal Forest Predictive Filter
    selected_with_cf_filter = causal_forest_predictive_filter(synthetic_data$X, X_tilde,
                                                              synthetic_data$y, synthetic_data$t, fdr_nominal = q, family = 'gaussian')
    current_fdp_cf = fdp(selected_with_cf_filter, synthetic_data$predictive)  # Compute FDP for Causal Forest
    current_power_cf = power(selected_with_cf_filter, synthetic_data$predictive)  # Compute Power for Causal Forest
    fdp_repeats_cf = c(fdp_repeats_cf, current_fdp_cf)
    power_repeats_cf = c(power_repeats_cf, current_power_cf)
  }
  
  # Compute mean and confidence intervals for Linear Model
  mean_fdp_lm = mean(fdp_repeats_lm)
  mean_power_lm = mean(power_repeats_lm)
  sd_fdp_lm = sd(fdp_repeats_lm)
  sd_power_lm = sd(power_repeats_lm)
  se_fdp_lm = sd_fdp_lm / sqrt(num_reps)
  se_power_lm = sd_power_lm / sqrt(num_reps)
  ci_fdp_lm = 1.96 * se_fdp_lm
  ci_power_lm = 1.96 * se_power_lm
  
  # Store results for Linear Model
  fdp_means_lm = c(fdp_means_lm, mean_fdp_lm)
  power_means_lm = c(power_means_lm, mean_power_lm)
  fdp_ci_lower_lm = c(fdp_ci_lower_lm, pmax(mean_fdp_lm - ci_fdp_lm, 0))  # Truncate lower bound
  fdp_ci_upper_lm = c(fdp_ci_upper_lm, pmin(mean_fdp_lm + ci_fdp_lm, 1))  # Truncate upper bound
  power_ci_lower_lm = c(power_ci_lower_lm, pmax(mean_power_lm - ci_power_lm, 0))  # Truncate lower bound
  power_ci_upper_lm = c(power_ci_upper_lm, pmin(mean_power_lm + ci_power_lm, 1))  # Truncate upper bound
  
  # Compute mean and confidence intervals for Causal Forest
  mean_fdp_cf = mean(fdp_repeats_cf)
  mean_power_cf = mean(power_repeats_cf)
  sd_fdp_cf = sd(fdp_repeats_cf)
  sd_power_cf = sd(power_repeats_cf)
  se_fdp_cf = sd_fdp_cf / sqrt(num_reps)
  se_power_cf = sd_power_cf / sqrt(num_reps)
  ci_fdp_cf = 1.96 * se_fdp_cf
  ci_power_cf = 1.96 * se_power_cf
  
  # Store results for Causal Forest
  fdp_means_cf = c(fdp_means_cf, mean_fdp_cf)
  power_means_cf = c(power_means_cf, mean_power_cf)
  fdp_ci_lower_cf = c(fdp_ci_lower_cf, pmax(mean_fdp_cf - ci_fdp_cf, 0))  # Truncate lower bound
  fdp_ci_upper_cf = c(fdp_ci_upper_cf, pmin(mean_fdp_cf + ci_fdp_cf, 1))  # Truncate upper bound
  power_ci_lower_cf = c(power_ci_lower_cf, pmax(mean_power_cf - ci_power_cf, 0))  # Truncate lower bound
  power_ci_upper_cf = c(power_ci_upper_cf, pmin(mean_power_cf + ci_power_cf, 1))  # Truncate upper bound
}
```




















































































































# q = 0.01
```{r}
q = 0.01
nIterations = 5
fdp_0.01 = c()
power_0.01 = c()
for (i in 1:nIterations){
  X_tilde = data.frame(create.second_order(as.matrix(synthetic_data$X)))
    selected_with_linear_filter = linear_model_predictive_filter(synthetic_data$X, X_tilde,synthetic_data$y, synthetic_data$t, fdr_nominal = q, family = 'gaussian')
  current_fdp =  fdp(selected_with_linear_filter, synthetic_data$predictive )
  current_power = power(selected_with_linear_filter, synthetic_data$predictive)
  fdr_0.01 = c(fdr_0.01, current_fdp)
  power_0.01 = c(power_0.01, current_power)
}
```

# q = 0.05
```{r}
q = 0.05
nIterations = 5
fdp_0.05 = c()
power_0.05 = c()
for (i in 1:nIterations){
  X_tilde = data.frame(create.second_order(as.matrix(synthetic_data$X)))
    selected_with_linear_filter = linear_model_predictive_filter(synthetic_data$X, X_tilde,synthetic_data$y, synthetic_data$t, fdr_nominal = q, family = 'gaussian')
  current_fdp =  fdp(selected_with_linear_filter, synthetic_data$predictive )
  current_power = power(selected_with_linear_filter, synthetic_data$predictive)
  fdr_0.05 = c(fdr_0.05, current_fdp)
  power_0.05 = c(power_0.05, current_power)
}
```


# q = 0.1
```{r}
q = 0.1
nIterations = 5
fdp_0.10 = c()
power_0.10 = c()
for (i in 1:nIterations){
  X_tilde = data.frame(create.second_order(as.matrix(synthetic_data$X)))
    selected_with_linear_filter = linear_model_predictive_filter(synthetic_data$X, X_tilde,synthetic_data$y, synthetic_data$t, fdr_nominal = q, family = 'gaussian')
  current_fdp =  fdp(selected_with_linear_filter, synthetic_data$predictive )
  current_power = power(selected_with_linear_filter, synthetic_data$predictive)
  fdr_0.10 = c(fdr_0.10, current_fdp)
  power_0.10 = c(power_0.10, current_power)
}
```

# q = 0.2
```{r}
q = 0.20
nIterations = 5
fdr_0.20 = c()
power_0.20 = c()
for (i in 1:nIterations){
  X_tilde = data.frame(create.second_order(as.matrix(synthetic_data$X)))
    selected_with_linear_filter = linear_model_predictive_filter(synthetic_data$X, X_tilde,synthetic_data$y, synthetic_data$t, fdr_nominal = q, family = 'gaussian')
  current_fdp =  fdp(selected_with_linear_filter, synthetic_data$predictive )
  current_power = power(selected_with_linear_filter, synthetic_data$predictive)
  fdr_0.20 = c(fdr_0.20, current_fdp)
  power_0.20 = c(power_0.20, current_power)
}
```

# q = 0.5
```{r}
q = 0.50
nIterations = 5
fdp_0.50 = c()
power_0.50 = c()
for (i in 1:nIterations){
  X_tilde = data.frame(create.second_order(as.matrix(synthetic_data$X)))
    selected_with_linear_filter = linear_model_predictive_filter(synthetic_data$X, X_tilde,synthetic_data$y, synthetic_data$t, fdr_nominal = q, family = 'gaussian')
  current_fdp =  fdp(selected_with_linear_filter, synthetic_data$predictive )
  current_power = power(selected_with_linear_filter, synthetic_data$predictive)
  fdp_0.50 = c(fdp_0.50, current_fdp)
  power_0.50 = c(power_0.50, current_power)
}
```

```{r}
mean_fdr0.01 = mean(fdp_0.01)
mean_fdr0.05 = mean(fdp_0.05)
mean_fdr0.1 = mean(fdp_0.10)
mean_fdr0.2 = mean(fdp_0.20)
mean_fdr0.5 = mean(fdp_0.50)
mean_power0.01 = mean(power_0.01)
mean_power0.05 = mean(power_0.05)
mean_power0.1 = mean(power_0.10)
mean_power0.2 = mean(power_0.20)
mean_power0.5 = mean(power_0.50)
```

```{r}
means_fdp = c(mean_fdr0.01,mean_fdr0.05,mean_fdr0.1,mean_fdr0.2,mean_fdr0.5)
means_power = c(mean_power0.01,mean_power0.05,mean_power0.1,mean_power0.2,mean_power0.5)
```


```{r}
nominals = c(0.01, 0.05, 0.1, 0.2, 0.5)
plot(nominals, means_fdp, type = "o", col = "red", pch = 16, lty = 1, 
     main = "Nominal q vs Mean FDP", xlab = "q", ylab = "Mean FDP", ylim = c(0, 0.6))

abline(0, 1, col = "black")

# Adding a legend
legend("topleft", legend = c("Mean FDP", "Y = X"), 
       col = c("red", "black"), pch = c(16, NA), lty = c(1, 1))

```

```{r}
plot(nominals,means_power,type = "o", col = "blue", pch = 16, lty = 1,main='nominal q vs mean power', xlab = 'q', ylab = 'mean power')
```

