---
title: "Schedis_vignette"
author: "Mark Milner"
date: "2025-02-17"
output: html_document
---

# taken from sechidis vignettes.

```{r}

#' The two predictive knockoff filters we presented in Section 2.3
#'
#'
#' @param X data.frame (or tibble) the input X, nrow(X) are the number of examples and ncol(X) the number of variables (features)
#' @param X_tilde data.frame (or tibble) the knockoffs of X.
#' @param y response vector with \code{length(y) = nrow(X)}. Accepts "numeric" (family="gaussian") or binary "factor" (family="binomial").
#' @param t treatment allocation binary vector with \code{length(t) = nrow(X)}. 
#' @param fdr_nominal target false discovery rate. Can be a vector of multiple thresholds.
#' @param family should be "gaussian" if y is numeric, but "binomial" if y is a binary factor variable.
#'
#' @return a vector of selected indices

# linear interaction KO filter (presented in Section 2.3.1)
linear_model_predictive_filter = function(X, X_tilde, y, t, fdr_nominal, family){
  
  p = dim(X)[2]
  
  # Combine the original Xs and their interactions T:X
  X_original_interactions = matrix(0, dim(X)[1], dim(X)[2])
  for (col in 1:p){
    X_original_interactions[,col]=  X[,col]*t
  }
  
  # Generate interactions with knockoffs the knockoffs Xs and their interactions T:X
  X_knockoffs_interactions = matrix(0, dim(X)[1], dim(X)[2])
  for (col in 1:p){
    X_knockoffs_interactions[,col] =  X_tilde[,col]*t
  }
  
  # Combine data
  X_combined = cbind(X, X_tilde, X_original_interactions, X_knockoffs_interactions, t)
  
  
  # Derive the variable importances
  X_combined = as.matrix(X_combined)
  y = as.matrix(y)
  models_glmnet_cv = glmnet::cv.glmnet(X_combined, y, family = family, nfolds=10, alpha = 1.0,  standardize=TRUE)
 
  importance_scores = coef(models_glmnet_cv, s = "lambda.1se")[2:(dim(X_combined)[2]+1)] # Ignore intercept
  
  # Derive W statistic only for the interaction terms
  W = abs(importance_scores[(2*p+1):(3*p)]) - abs(importance_scores[(3*p+1):(4*p)])
  
  # Calculate the threshold
  threshold = knockoff::knockoff.threshold(W, fdr=fdr_nominal)
  # Find the selected features
  selected_features = which(W >= threshold)
  
  return(selected_features)
  
}
```

```{r}
#' Simulates the scenarios of Section 3
#'
#'
#' @param scenario an integer that represents the scenario we explore in the paper, eg. scenario=1, simulates the scenario of Section 3.4.1, scenario=2, simulates the scenario of Section 3.4.2 etc
#' @param model an integer that represents the model from which we simulate the data, eg model=1, model=2 etc 
#' @param predictive_amplitude a number that captures the strength of the predictive signal, e.g. the parameter theta_pred of the paper
#' @param sample_size the number of exmamples (e.g. patients)
#' @param num_features the number of variables (features, covarietes)
#' 
#' @return the simulated data 
generate_scenarios_predictive = function(scenario, model, sample_size, num_features, predictive_amplitude) {
  
  
  if(scenario == 'S1')
  {
    # Sample T:
    prob_t = 0.50 
    t = rbinom(sample_size,1,prob_t)
    # Sample Xs
    rho = 0.50
    sigma_z =  toeplitz(rho^(0:(num_features - 1)))
    X = data.frame(mvtnorm::rmvnorm(sample_size, rep(0, num_features), sigma_z, "chol"))
    # Generate y
    if(model=='M1')
    {
      nonzero_pred = seq(1,10,1)
      nonzero_prog = seq(11,20,1)
      prog_part = apply(X[,nonzero_prog],1,sum)
      pred_part = predictive_amplitude*t*(apply(X[,nonzero_pred],1,sum))
      mu = 0.5*t + as.numeric(as.matrix((prog_part)) + as.matrix((pred_part)) )
      y = mu + matrix(rnorm(sample_size, mean = 0, sd = 1), sample_size, 1)
    }
    
    if(model=='M2')
    {
      nonzero_pred = seq(1,10,1)
      nonzero_prog = seq(1,10,1)
      prog_part = apply(X[,nonzero_prog],1,sum)
      pred_part = predictive_amplitude*t*(apply(X[,nonzero_pred],1,sum))
      mu = 0.5*t + as.numeric(as.matrix((prog_part)) + as.matrix((pred_part)) )
      y = mu + matrix(rnorm(sample_size, mean = 0, sd = 1), sample_size, 1)
    }
    
    if(model=='M3')
    {
      nonzero_pred = seq(1,5,1)
      nonzero_prog = seq(1,10,1)
      prog_part = apply(X[,nonzero_prog],1,sum)
      pred_part = predictive_amplitude*t*(apply(X[,nonzero_pred],1,sum))
      mu = 0.5*t + as.numeric(as.matrix((prog_part)) + as.matrix((pred_part)) )
      y = mu + matrix(rnorm(sample_size, mean = 0, sd = 1), sample_size, 1)
    }
    
    if(model=='M4')
    {
      nonzero_pred = seq(1,10,1)
      nonzero_prog = seq(1,5,1)
      prog_part = apply(X[,nonzero_prog],1,sum)
      pred_part = predictive_amplitude*t*(apply(X[,nonzero_pred],1,sum))
      mu = 0.5*t + as.numeric(as.matrix((prog_part)) + as.matrix((pred_part)) )
      y = mu + matrix(rnorm(sample_size, mean = 0, sd = 1), sample_size, 1)
    }
    
    if(model=='M5')
    {
      nonzero_pred = seq(1,10,1)
      nonzero_prog = 0
      prog_part = apply(X[,nonzero_prog],1,sum)
      pred_part = predictive_amplitude*t*(apply(X[,nonzero_pred],1,sum))
      mu = 0.5*t + as.numeric(as.matrix((prog_part)) + as.matrix((pred_part)) )
      y = mu + matrix(rnorm(sample_size, mean = 0, sd = 1), sample_size, 1)
    }
    
    if (predictive_amplitude == 0) {nonzero_pred = 0}
  }
  
  
  
  if(scenario == 'S2')
  {
    # Sample t
    prob_t = 0.50 
    t = rbinom(sample_size,1,prob_t)
    # Sample Xs
    rho = 0.50
    sigma_z =  toeplitz(rho^(0:(num_features - 1)))
    X = data.frame(mvtnorm::rmvnorm(sample_size, rep(0, num_features), sigma_z, "chol"))
    # Generate y 
    if(model=='M1')
    {
      nonzero_pred = seq(1,10,1)
      nonzero_prog = seq(6,15,1)
      prog_part = (apply(exp(matrix(runif(sample_size*length(nonzero_prog),0.50,1.50), sample_size, length(nonzero_prog))*X[,nonzero_prog]),1,sum))
      if(predictive_amplitude == 0 ){
        mu = 0.5*t + as.numeric(as.matrix((prog_part)))
        y = mu + matrix(rnorm(sample_size, mean = 0, sd = 1), sample_size, 1)
      }
      
      if(predictive_amplitude !=0){
        pred_part = predictive_amplitude*t*(apply(exp(kronecker(t(runif(length(nonzero_pred),0.50,1.50)), matrix(1, sample_size, 1))*X[,nonzero_pred]),1,sum))
        mu = 0.5*t + as.numeric(as.matrix((prog_part)) + as.matrix((pred_part)) )
        y = mu + matrix(rnorm(sample_size, mean = 0, sd = 1), sample_size, 1)
      }
    }
    
    if(model=='M2')
    {
      nonzero_pred = seq(1,10,1)
      nonzero_prog = seq(6,15,1)
      prog_part = X[,nonzero_prog[1]] * X[,nonzero_prog[2]] + X[,nonzero_prog[3]]*X[,nonzero_prog[4]] + X[,nonzero_prog[5]]*X[,nonzero_prog[6]]+ X[,nonzero_prog[7]]*X[,nonzero_prog[8]] + X[,nonzero_prog[9]]*X[,nonzero_prog[10]] 
      if(predictive_amplitude == 0){
        mu = 0.5*t + as.numeric(as.matrix((prog_part)))
        y = mu + matrix(rnorm(sample_size, mean = 0, sd = 1), sample_size, 1)
      }
      
      if(predictive_amplitude != 0 ){
        pred_part = X[,nonzero_pred[1]] * X[,nonzero_pred[2]] + X[,nonzero_pred[3]]*X[,nonzero_pred[4]] + X[,nonzero_pred[5]]*X[,nonzero_pred[6]]+ X[,nonzero_pred[7]]*X[,nonzero_pred[8]] + X[,nonzero_pred[9]]*X[,nonzero_pred[10]]
        pred_part = predictive_amplitude*t*pred_part
        mu = 0.5*t + as.numeric(as.matrix((prog_part)) + as.matrix((pred_part)) )
        y = mu + matrix(rnorm(sample_size, mean = 0, sd = 1), sample_size, 1)
      }
    }
    
    if(model=='M3')
    {
      nonzero_pred = seq(1,10,1)
      nonzero_prog = seq(6,15,1)
      prog_part = X[,nonzero_prog[1]] + X[,nonzero_prog[2]]^2 + X[,nonzero_prog[3]]^3 + X[,nonzero_prog[4]]*X[,nonzero_prog[5]] + X[,nonzero_prog[6]]*X[,nonzero_prog[7]] + X[,nonzero_prog[8]]*X[,nonzero_prog[9]]*X[,nonzero_prog[10]]
      if(predictive_amplitude == 0 ){
        mu = 0.5*t + as.numeric(as.matrix((prog_part)))
        y = mu + matrix(rnorm(sample_size, mean = 0, sd = 1), sample_size, 1)
      }
      
      if(predictive_amplitude != 0){
        pred_part = X[,nonzero_pred[1]] + X[,nonzero_pred[2]]^2 + X[,nonzero_pred[3]]^3 + X[,nonzero_pred[4]]*X[,nonzero_pred[5]] + X[,nonzero_pred[6]]*X[,nonzero_pred[7]] + X[,nonzero_pred[8]]*X[,nonzero_pred[9]]*X[,nonzero_pred[10]]
        pred_part = predictive_amplitude*t*pred_part
        mu =  0.5*t + as.numeric(as.matrix((prog_part)) + as.matrix((pred_part)) )
        y = mu + matrix(rnorm(sample_size, mean = 0, sd = 1), sample_size, 1)
      }
    }
    
    if (predictive_amplitude == 0) {nonzero_pred = 0}
  }
  
  
  
  if(scenario == 'S3')
  {
    # Sample t
    prob_t = 0.50 
    t = rbinom(sample_size,1,prob_t)
    # Sample Xs
    rho = 0.50
    sigma_z =  toeplitz(rho^(0:(num_features - 1)))
    X = data.frame(mvtnorm::rmvnorm(sample_size, rep(0, num_features), sigma_z, "chol"))
    # Generate y
    if(model=='M1')
    {
      nonzero_pred = seq(1,5,1)
      nonzero_prog = seq(1,5,1)
      prog_part =   X[,nonzero_prog[1]] + X[,nonzero_prog[2]] + X[,nonzero_prog[3]] + X[,nonzero_prog[4]] + X[,nonzero_prog[5]]
      if(predictive_amplitude == 0 ){
        mu = 0.5*t + as.numeric(as.matrix((prog_part)))
        y = mu + matrix(rnorm(sample_size, mean = 0, sd = 1), sample_size, 1)
      }
      
      if(predictive_amplitude != 0){
        pred_part = (X[,nonzero_pred[1]]>0) + (X[,nonzero_pred[2]]<0) + (X[,nonzero_pred[3]]<0.675) + (X[,nonzero_pred[4]]>0.675) + (X[,nonzero_pred[5]]<0.675)
        pred_part = predictive_amplitude*t*pred_part
        mu = 0.5*t + as.numeric(as.matrix((prog_part)) + as.matrix((pred_part)) )
        y = mu + matrix(rnorm(sample_size, mean = 0, sd = 1), sample_size, 1)
      }
    }
    
    if(model=='M2')
    {
      nonzero_pred = seq(1,5,1)
      nonzero_prog = seq(1,5,1)
      prog_part =   X[,nonzero_prog[1]] + X[,nonzero_prog[2]] + X[,nonzero_prog[3]] + X[,nonzero_prog[4]] + X[,nonzero_prog[5]]
      if(predictive_amplitude == 0){
        mu = 0.5*t + as.numeric(as.matrix((prog_part)))
        y = mu + matrix(rnorm(sample_size, mean = 0, sd = 1), sample_size, 1)
      }
      if(predictive_amplitude != 0){
        pred_part = abs(X[,nonzero_pred[1]])* (X[,nonzero_pred[2]]>0.675) + abs(X[,nonzero_pred[3]])*(X[,nonzero_pred[4]]<0)*(X[,nonzero_pred[5]]>0)
        pred_part = predictive_amplitude*t*pred_part
        mu = 0.5*t + as.numeric(as.matrix((prog_part)) + as.matrix((pred_part)) )
        y = mu + matrix(rnorm(sample_size, mean = 0, sd = 1), sample_size, 1)
      }
    }
    if (predictive_amplitude == 0) {nonzero_pred = 0}
  }
  
  
  if(scenario == 'S4')
  {
    
    if(model=='M1')
    { 

      # Sample t
      prob_t = 0.50 
      t = rbinom(sample_size,1,prob_t)
      # Sample Xs
      rho = 0.50
      sigma_z =  toeplitz(rho^(0:(num_features - 1)))
      X = data.frame(mvtnorm::rmvnorm(sample_size, rep(0, num_features), sigma_z, "chol"))
      # Generate y
      nonzero_pred = seq(1,10,1)
      nonzero_prog = seq(11,20,1)
      prog_part = apply(X[,nonzero_prog],1,sum)
      pred_part = predictive_amplitude*t*(apply(X[,nonzero_pred],1,sum))
      mu = 0.5*t + as.numeric(as.matrix((prog_part)) + as.matrix((pred_part)) )
      y = mu + matrix(rnorm(sample_size, mean = 0, sd = 1), sample_size, 1)
    }
    
    if(model=='M2')
    {     

      # Sample t
      prob_t = 0.50 
      t = rbinom(sample_size,1,prob_t)
      # Sample Xs
      rho = 0.50
      sigma_z =  toeplitz(rho^(0:(num_features - 1)))
      X = data.frame(mvtnorm::rmvnorm(sample_size, rep(0, num_features), sigma_z, "chol"))
      # Generate y
      nonzero_pred = seq(1,10,1)
      nonzero_prog = seq(6,15,1)
      prog_part = X[,nonzero_prog[1]] * X[,nonzero_prog[2]] + X[,nonzero_prog[3]]*X[,nonzero_prog[4]] + X[,nonzero_prog[5]]*X[,nonzero_prog[6]]+ X[,nonzero_prog[7]]*X[,nonzero_prog[8]] + X[,nonzero_prog[9]]*X[,nonzero_prog[10]] 
      if(predictive_amplitude == 0){
        mu = 0.5*t + as.numeric(as.matrix((prog_part)))
        y = mu + matrix(rnorm(sample_size, mean = 0, sd = 1), sample_size, 1)
      }
      if(predictive_amplitude != 0 ){
        pred_part = X[,nonzero_pred[1]] * X[,nonzero_pred[2]] + X[,nonzero_pred[3]]*X[,nonzero_pred[4]] + X[,nonzero_pred[5]]*X[,nonzero_pred[6]]+ X[,nonzero_pred[7]]*X[,nonzero_pred[8]] + X[,nonzero_pred[9]]*X[,nonzero_pred[10]] 
        pred_part = predictive_amplitude*t*pred_part
        mu = 0.5*t + as.numeric(as.matrix((prog_part)) + as.matrix((pred_part)) )
        y = mu + matrix(rnorm(sample_size, mean = 0, sd = 1), sample_size, 1)
      }
    }
    if (predictive_amplitude == 0) {nonzero_pred = 0}
  }
  
  output = c()
  output$t = t
  output$X = X
  output$y = y[,1]
  
  output$predictive = nonzero_pred

  
  return(output)
}
```

```{r}
library(glmnet) # is needed for the linear interaction KO filter 
#library(grf) # is needed for the causal forest (CF) variable importance KO filter 
library(knockoff) # is needed for generating the knockoffs and calculating the threshold
```

```{r}
# Generate data from Scenario 2, Model 1 with  amplitude of the predictive signal 1. For this example we generated 500 examples (patients) and 100 features (markers)
synthetic_data = generate_scenarios_predictive(scenario = 'S2', model = 'M1', 
sample_size = 1000, num_features = 100, predictive_amplitude = 1)
paste('In this synthetic dataset the following variables are predictive:', 
paste(synthetic_data$predictive, collapse=","))
```
```{r}
X_tilde = data.frame(create.second_order(as.matrix(synthetic_data$X)))
```

```{r}
selected_with_linear_filter = linear_model_predictive_filter(synthetic_data$X, X_tilde,
synthetic_data$y, synthetic_data$t, fdr_nominal = 0.20, family = 'gaussian')
paste('The linear interaction KO filter returns the variables:',
paste(selected_with_linear_filter, collapse=","))
```



# Causal Forest test


