---
title: "Experiment3"
author: "Mark Milner"
date: "2025-01-31"
output: html_document
---

This experiment considers changing the number of covatiates included in the model.

```{r}
library(knockoff)
```

```{r}
fdp = function(selected) sum(beta[selected] == 0) / max(1, length(selected))
```

```{r}
power = function(selected) {
  # True Positives: selected variables with non-zero coefficients
  TP = sum(beta[selected] != 0)
  
  # Total Relevant Variables
  T = sum(beta != 0)
  
  # Compute Power
  TP / T
}
```

## Data Setup 

```{r}
set.seed(21)
```

```{r}
generate_synthetic_data <- function(n=1000, p=1000, relevant_count=100, amplitude=4.5, rho=0.25) {
  mu = rep(0,p)
  Sigma = toeplitz(rho^(0:(p-1)))
  X = matrix(rnorm(n*p),n) %*% chol(Sigma)
  nonzero = sample(p, relevant_count)
  beta = amplitude * (1:p %in% nonzero) / sqrt(n)
  y =  X %*% beta + rnorm(n)
  list(X = X, y = y, beta=beta)
}
```

# Implimentation 

```{r}
covariate_counts = c(100,200,500,1000)
fdp_s = c()
power_s = c()
for (covariate_count in covariate_counts){
  data <- generate_synthetic_data(p=covariate_count)
  X <- data$X
  y <- data$y
  beta = data$beta
  result = knockoff.filter(X, y)
  current_fdp = fdp(result$selected)
  current_power = power(result$selected)
  fdp_s = c(fdp_s, current_fdp)
  power_s = c(power_s, current_power)
}
```

# visualisation 

```{r}
plot(covariate_counts, fdp_s, type = "o", col = "red", pch = 16, lty = 1,
     xlab = "p", ylab = "FDP",
     main = "FDP vs number of covariates (p)")

plot(covariate_counts, power_s, type = "o", col = "blue", pch = 16, lty = 1,
     xlab = "p", ylab = "Power",
     main = "Power vs number of covariates (p)")
```




